Portfolio continuation
essiewanjiru99/essie-portfolio pull request #2
Opened 2023-06-01 20:53 UTC by essiewanjiru99

I used the following to continue building my portfolio;

- Added index.css
- Added index.html
- l used linters

2023-06-01 21:25 UTC, Kossi-stack requested changes
## Hi @essiewanjiru99,

**Good job so far! 👍🏻**
There are some issues that you still need to work on to go to the next project but you are almost there!💪

![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966](https://user-images.githubusercontent.com/81444338/170121142-a9f93bb7-38bb-45cc-8327-aab2501ef90a.gif)

## To Highlight

✅ Descriptive pull request message
✅ Linter error checks validated
✅ Documented your work professionally
✅ README file is descriptive.
✅ Commit messages are meaningful.

## Required Changes ♻️

 - [ ] Kindly edit the PR's title to something more descriptive. it can be "Portfolio: finish mobile version Project".
 - [ ] Kindly make sure next time you make your Readme file available in the branch for review purposes, remove the live demo section since it is not available.
 
 _Check the comments under the review for more changes_.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-06-01 21:25 UTC, Kossi-stack commented on index.html
> +    <section class="line-break">
- [ ]Kindly make sure to have only one section for my recent works. For clean code purposes

2023-06-01 21:25 UTC, Kossi-stack commented on index.html
> +
- [ ] Kindly remove the empty line in your code it help you to have clean code

2023-06-01 21:25 UTC, Kossi-stack commented on index.html
> +            <h1>Multi-Post Stories <br> Gain+Glory</h1>
- [ ] Kindly use another heading like h2 ...... hx for subtitles. Use h1 only for the main Title.

2023-06-01 21:25 UTC, Kossi-stack commented on index.html
> +            <h1>Multi-Post Stories <br> Gain+Glory</h1>
- [ ] Kindly use another heading like h2 ...... hx for subtitles. Use h1 only for the main Title.

2023-06-01 21:25 UTC, Kossi-stack commented on index.html
> +
- [ ] Kindly remove the empty line in your code it helps you to have clean code

2023-06-01 21:25 UTC, Kossi-stack commented on index.html
> +                  <p>Language</p>
- [ ] Kindly make sure the technology categories ("Languages", "Frameworks" and "Skills") are in a ul, each of them in a li

2023-06-02 06:45 UTC, NatiG25 requested changes
## :yellow_circle: CHANGES REQUIRED :yellow_circle: 

## Hi @essiewanjiru99 :wave:, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Highlights
:heavy_check_mark: Good job! Using only one `h1`.
:heavy_check_mark: Remove empty lines.

![](https://media.giphy.com/media/z3piokwf0WPH81MOhu/giphy.gif)

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-02 06:45 UTC, NatiG25 commented on index.html
> +                      <ul>
- [ ] As mentioned by the previous reviewer, you should have:
- Your technology categories ("Languages", "Frameworks" and "Skills") in a `ul`, & each of them in a `li`. 
- The technologies in each category(e.g., "JavasScript", "HTML" and "CSS") should also be in a `ul` and each of them in a `li`

2023-06-02 09:35 UTC, Owusu-Desmond approved these changes
Hi @essiewanjiru99 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media4.giphy.com/media/j3uHCOkxs83d5nXJAX/giphy.gif"/>

## Highlights
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Good commit messages ✅
📌 Professional README file ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-02 09:40 UTC, merged