Portfolio: desktop version
essiewanjiru99/essie-portfolio pull request #4
Opened 2023-06-08 16:48 UTC by essiewanjiru99

In this PR, I was able to work with:
- Media queries for desktop and tablet sizes.
- Display block and none.
- Display grid and flex for laying out the features in the Desktop view.

2023-06-08 16:58 UTC, Ofarouq310 reviewed
Hi @essiewanjiru99, ✋ 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

![giphy](https://github.com/essiewanjiru99/essie-portfolio/assets/102612396/7bbada57-f6ee-4b2c-adc9-b1ab974ad2f5)

## 🔴 Invalid Code Review Request

- You have submitted a project, that does not contain a descriptive PR summary, you have to summarize what you implemented in the project using a bullet list, a checklist, or a numbers list, in your case it could be something like:

    - Added a header section to the portfolio,
    - Added a headline section with an introduction paragraph.
    - etc...

customize it to your project's implementations.

- Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-06-08 20:11 UTC, shahadat3669 requested changes
Hi @essiewanjiru99 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media1.giphy.com/media/m3864rBwwBTKMAbpn3/giphy.gif"/>

## Highlights
Correct use of GitHub Flow ✅
Well-structured files ✅
All linter checks are passing ✅
Descriptive PR title with a great summary ✅

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [Optional] Your Readme looks good. You have a heading named "FAQ" in your "Table of contents". But there is no "FAQ" section in your readme file. Please consider removing it as it could lead visitors to a miscommunication. 🙏 
![image](https://github.com/essiewanjiru99/essie-portfolio/assets/55840999/9f4f7d71-217e-4ae3-9b32-e0360cdde452)
- [Optional] In the author section of the readme file you added your social links. 👍 but instead of "Authro1" you should type your name. It will be professional by doing so.
![image](https://github.com/essiewanjiru99/essie-portfolio/assets/55840999/e67dd1f8-a5a5-4ebe-9883-6bc651db19af)

Cheers and Happy coding!👏👏👏

## Have any doubt ❓


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

## ⚠️ WARNING ⚠️
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-08 20:11 UTC, shahadat3669 commented on index.html
### Recent Work/Project Section
- [ ] Well done! 👍 You have a "div" with the class "line-break" that contains the recent work titles. However, there are a couple of adjustments needed. Firstly, it should be placed inside the section with the class name "section-placeholder" as it represents that section. Secondly, in the desktop version, according to the design, the titles should be displayed in a single line, but on your webpage, they are displayed on two lines.

- [ ] As previously mentioned, since you are building a responsive website, your project section should match the mobile version from 375px to 768px, where all cards should be centered at all times. On the other hand, from 768px and up, your webpage should follow the desktop version, where the cards should be displayed in two rows, with each row containing four cards, and all of them should be centered. Please ensure your code aligns with the design.

Here is an image showcasing the issue in the Recent Work/Project section: 

[Document (6).webm](https://github.com/essiewanjiru99/essie-portfolio/assets/55840999/33b564de-d184-430a-92f8-b0fd66b34bc4)

### About Me Section
- [ ] In the About Me section, the title and paragraph look good. However, each card in this section should have proper spacing, as per the design, which is currently missing.

- [ ] Additionally, in the desktop version, the title and paragraph should be center-aligned, as per the design. Please update your code accordingly. 🙏

- [ ] Similarly, all the cards should be displayed in a single row, centered as per the design, but currently, they are not aligned properly.

Here is an image showcasing the issues in the About Me section: 

[Document (5).webm](https://github.com/essiewanjiru99/essie-portfolio/assets/55840999/133748f1-0a25-4b3f-80b0-af8f2cc54e18)


### Contact Me Section
- [ ] In the mobile version, your Contact Me section looks good in different screen sizes. However, in the desktop version, your title and form do not align with the design. Please carefully review the design and update your code. 🙏

- [ ] Additionally, in the desktop version, the background is overlapping with the content in some cases, making it difficult to read the content. Please address this issue.

Here is an image showcasing the issues in the Contact Me section: 

[Document (8).webm](https://github.com/essiewanjiru99/essie-portfolio/assets/55840999/781ead34-19c2-4015-99bb-21f932048927)

Taking care of these adjustments will enhance the overall visual consistency and user experience of your webpage. Keep up the good work! 👍🌟

2023-06-09 07:53 UTC, shahadat3669 requested changes
Hi @essiewanjiru99 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
Correct use of GitHub Flow ✅
Well-structured files ✅
All linter checks are passing ✅
Descriptive PR title with a great summary ✅

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-09 07:53 UTC, shahadat3669 commented on index.html
> +    <div class="project-cards">
Well done! As per the previous review, you made significant improvements to your cards. However, there are still some adjustments needed:

- [ ] For the mobile design, the card section should have 24px padding on the left and right sides. Currently, it is missing in your code. Additionally, I noticed that you have fixed dimensions for the cards, which can cause a vertical scrollbar to appear when padding is added. To solve this, you can use approaches like combining min-width and max-width or using responsive values in your CSS rules, such as percentages (e.g., width: 80%). Please consider updating your code. 🙏
- [ ] The gap between the cards should be 24px as per the design, but currently, it is set to 20px. Please adjust it accordingly. 🙏
- [ ] Each tag should have 12px padding on the left and right sides, but you have it set to 18px. Please update it to match the design requirements.
- [ ] There should be a gap after the button, but currently, there is none. Please add an appropriate gap according to the design.


![Frame 37](https://github.com/essiewanjiru99/essie-portfolio/assets/55840999/f0cde79c-28d3-4280-abcb-879d9bb00edc)

Thank you for your hard work! 🙏

2023-06-09 07:53 UTC, shahadat3669 commented on index.html
> +        </li>
Great job on improving your About Me section! However, a few new issues have emerged that need attention:

- [ ] Each card should have a left and right margin of 24px, but currently, it is set to 0 in your code. Please update your code to match the design requirements.
- [ ] Please ensure that you use proper padding and spacing for lists. Check the design and adjust your code accordingly.
- [ ] The gap between skill cards does not match the design. Please update the gap between the skill cards to align with the design.

![Frame 38 (1)](https://github.com/essiewanjiru99/essie-portfolio/assets/55840999/514549c6-3c3d-42b9-bcf1-b3c3f2001adb)

Keep up the good work and continue refining your project! 👍

2023-06-09 10:13 UTC, merged